server:
  port: 8080

spring-cloud-ribbon-user:
  ribbon:
    eager-load:
      enabled: true # 开启饥饿加载
    eureka:
      enabled: false
    listOfServers: localhost:8081,localhost:8082
    ServerListRefreshInterval: 5000
    NFLoadBalancerRuleClassName: com.bruce.ribbon.rule.MyRule
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.AvailabilityFilteringRule # 负载均衡规则
#    NFLoadBalancerPingClassName: com.netflix.loadbalancer.PingUrl



logging:
  level:
    com.netflix.loadbalancer.BaseLoadBalancer: debug
