package com.bruce.html;

/**
 * @author rcy
 * @data 2021-12-12 23:38
 * @description TODO
 */
public class HtmlStr {

    public static String getHtmlStr() {
        StringBuilder sb = new StringBuilder();

        sb.append("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">")
                .append("<html lang=\"en\" xmlns=\"http://www.w3.org/1999/xhtml\">")
                .append("<head>")
                .append("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\"/>")
                .append("</head>")
                .append("<body>")
                .append("<div class=\"sell\" style=\"background-color: #ffffff;\">")
                .append("<p style=\"margin:30pt 0 0 0; orphans:0; text-align:center; widows:0;font-family:宋体; font-size:18pt\">")
                .append("深圳市海王优品健康科技有限公司销售合同")
                .append("</p>")
                .append("<div style=\"width: 1080px;margin: 0 auto;\">")
                .append("<div style=\"display: flex;margin-top: 30px;\">")
                .append("<div style=\"font-family:新宋体; font-size:12pt\">运输到站</div>")
                .append("<div style=\"font-family:新宋体; font-size:12pt;border-bottom: 1px solid #000;min-width:160px;height:12pt\"></div>")
                .append("<div style=\"font-family:新宋体; font-size:12pt\">运输方式</div>")
                .append("<div style=\"font-family:新宋体; font-size:12pt;border-bottom: 1px solid #000;min-width:160px;height:12pt\"></div>")
                .append("</div>")
                .append("<div style=\"display: flex;font-family:新宋体; font-size:12pt;margin-top: 10px;\">")
                .append("收货地址")
                .append("<div style=\"font-family:新宋体; font-size:12pt;border-bottom: 1px solid #000;min-width:385px;height:12pt\">")
                .append("${recive_addr}")
                .append("</div>")
                .append("</div>")
                .append("<div style=\"display: flex;font-family:新宋体; font-size:12pt;margin-top: 10px;\">")
                .append("签订日期")
                .append("<div style=\"min-width: 80px;border-bottom: 1px solid #000;font-family:新宋体; font-size:12pt;\">")
                .append("${qd_year}")
                .append("</div>")
                .append("年")
                .append("<div style=\"min-width: 80px;border-bottom: 1px solid #000;font-family:新宋体; font-size:12pt;\">")
                .append("${qd_month}")
                .append("</div>")
                .append("月")
                .append("<div style=\"min-width: 80px;border-bottom: 1px solid #000;font-family:新宋体; font-size:12pt;\">")
                .append("${qd_date}")
                .append("</div>")
                .append("日")
                .append("<div style=\"margin-left: 110px;font-family:新宋体; font-size:12pt;\">销售订单号：</div>")
                .append("<div style=\"font-family:新宋体; font-size:12pt;min-width: 160px;border-bottom: 1px solid #000;\">${order_no}")
                .append("</div>")
                .append("</div>")
                .append("<div style=\"display: flex;font-family:新宋体; font-size:12pt;margin-top: 10px;\">")
                .append("履行期限")
                .append("<div style=\"min-width: 80px;border-bottom: 1px solid #000;font-family:新宋体; font-size:12pt;\"></div>")
                .append("年")
                .append("<div style=\"min-width: 80px;border-bottom: 1px solid #000;font-family:新宋体; font-size:12pt;\"></div>")
                .append("月")
                .append("<div style=\"min-width: 80px;border-bottom: 1px solid #000;font-family:新宋体; font-size:12pt;\"></div>")
                .append("日至")
                .append("<div style=\"min-width: 80px;border-bottom: 1px solid #000;font-family:新宋体; font-size:12pt;\"></div>")
                .append("年")
                .append("<div style=\"min-width: 80px;border-bottom: 1px solid #000;font-family:新宋体; font-size:12pt;\"></div>")
                .append("月")
                .append("<div style=\"min-width: 80px;border-bottom: 1px solid #000;font-family:新宋体; font-size:12pt;\"></div>")
                .append("日")
                .append("</div>")
                .append("<div style=\"display: flex;font-family:新宋体; font-size:12pt;margin-top: 10px;\">")
                .append("结算方式")
                .append("<div style=\"min-width: 185px;border-bottom: 1px solid #000;font-family:新宋体; font-size:12pt;\"></div>")
                .append("<div style=\"margin-left: 65px;font-family:新宋体; font-size:12pt;\">付款方式：</div>")
                .append("<input type=\"checkbox\" checked=\"checked\"/>电汇")
                .append("<input type=\"checkbox\" checked=\"checked\"/>银行承兑汇票")
                .append("</div>")
                .append("<table cellspacing=\"0\" cellpadding=\"0\" style=\"border-collapse:collapse;\">")
                .append("<tr style=\"height:30.95px\">")
                .append("<td style=\" border-left-color:#000000; border-left-style:solid; border-left-width:0.75px; border-top-color:#000000; border-top-style:solid; border-top-width:0.75px; padding-left:0.12px; padding-right:0.5px; vertical-align:middle; width:157.15px\">")
                .append("<p style=\"margin:0px; orphans:0; text-align:center; widows:0\">")
                .append("<span style=\"font-family:宋体; font-size:11px\">品名</span>")
                .append("</p>")
                .append("</td>")
                .append("<td style=\" border-left-color:#000000; border-left-style:solid; border-left-width:0.75px; border-top-color:#000000; border-top-style:solid; border-top-width:0.75px; padding-left:0.12px; padding-right:0.5px; vertical-align:middle; width:78.7px\">")
                .append("<p style=\"margin:0px 0px 0px 3px; orphans:0; text-align:center; widows:0\">")
                .append("<span style=\"font-family:宋体; font-size:11px\">规格</span>")
                .append("</p>")
                .append("</td>")
                .append("<td style=\" border-left-color:#000000; border-left-style:solid; border-left-width:0.75px; border-top-color:#000000; border-top-style:solid; border-top-width:0.75px; padding-left:0.12px; padding-right:0.5px; vertical-align:middle; width:37.4px\">")
                .append("<p style=\"margin:0px; orphans:0; text-align:center; widows:0\">")
                .append("<span style=\"font-family:宋体; font-size:11px\">单位</span>")
                .append("</p>")
                .append("</td>")
                .append("<td style=\" border-left-color:#000000; border-left-style:solid; border-left-width:0.75px; border-top-color:#000000; border-top-style:solid; border-top-width:0.75px; padding-left:0.12px; padding-right:0.5px; vertical-align:middle; width:62.1px\">")
                .append("<p style=\"margin:0px; orphans:0; text-align:center; widows:0\">")
                .append("<span style=\"font-family:宋体; font-size:11px\">供货单价</span>")
                .append("</p>")
                .append("<p style=\"margin:0px; orphans:0; text-align:center; widows:0\">")
                .append("<span style=\"font-family:宋体; font-size:11px\">（含税）</span>")
                .append("</p>")
                .append("</td>")
                .append("<td style=\" border-left-color:#000000; border-left-style:solid; border-left-width:0.75px; border-top-color:#000000; border-top-style:solid; border-top-width:0.75px; padding-left:0.12px; padding-right:0.5px; vertical-align:middle; width:65.95px\">")
                .append("<p style=\"margin:0px; orphans:0; text-align:center; widows:0\">")
                .append("<span style=\"font-family:宋体; font-size:11px\">供货数量</span>")
                .append("</p>")
                .append("</td>")
                .append("<td style=\" border-left-color:#000000; border-left-style:solid; border-left-width:0.75px; border-top-color:#000000; border-top-style:solid; border-top-width:0.75px; padding-left:0.12px; padding-right:0.5px; vertical-align:middle; width:59.7px\">")
                .append("<p style=\"margin:0px; orphans:0; text-align:center; widows:0\">")
                .append("<span style=\"font-family:宋体; font-size:11px\">金额合计（含税）</span>")
                .append("</p>")
                .append("</td>")
                .append("<td style=\" border-left-color:#000000; border-left-style:solid; border-left-width:0.75px; border-right-color:#000000; border-right-style:solid; border-right-width:0.75px; border-top-color:#000000; border-top-style:solid; border-top-width:0.75px; padding-left:0.12px; padding-right:0.12px; vertical-align:middle; width:51.3px\">")
                .append("<p style=\"margin:0px; orphans:0; text-align:center; widows:0\">")
                .append("<span style=\"font-family:宋体; font-size:11px\">备注</span>")
                .append("</p>")
                .append("</td>")
                .append("</tr>")
                .append("<tr style=\"height:23.3px\">")
                .append("<td style=\"  border-left-color:#000000; border-left-style:solid; border-left-width:0.75px; border-right-color:#000000; border-right-style:solid; border-right-width:0.75px; border-top-color:#000000; border-top-style:solid; border-top-width:0.75px; padding-left:0.12px; padding-right:0.5px; vertical-align:top; width:157.15px\">")
                .append("<p style=\"margin:5px 0px 0px; orphans:0; text-align:center; widows:0\">")
                .append("<span style=\"font-family:宋体; font-size:11px\">${item.name}</span>")
                .append("</p>")
                .append("</td>")
                .append("<td style=\"  border-left-color:#000000; border-left-style:solid; border-left-width:0.75px; border-right-color:#000000; border-right-style:solid; border-right-width:0.75px; border-top-color:#000000; border-top-style:solid; border-top-width:0.75px; padding-left:0.12px; padding-right:0.5px; vertical-align:top; width:157.15px\">")
                .append("<p style=\"margin:5px 0px 0px; orphans:0; text-align:center; widows:0\">")
                .append("<span style=\"font-family:宋体; font-size:11px\">${item.spec}</span>")
                .append("</p>")
                .append("</td>")
                .append("<td style=\"  border-left-color:#000000; border-left-style:solid; border-left-width:0.75px; border-right-color:#000000; border-right-style:solid; border-right-width:0.75px; border-top-color:#000000; border-top-style:solid; border-top-width:0.75px; padding-left:0.12px; padding-right:0.5px; vertical-align:top; width:157.15px\">")
                .append("<p style=\"margin:5px 0px 0px; orphans:0; text-align:center; widows:0\">")
                .append("<span style=\"font-family:宋体; font-size:11px\">${item.unit}</span>")
                .append("</p>")
                .append("</td>")
                .append("<td style=\"  border-left-color:#000000; border-left-style:solid; border-left-width:0.75px; border-right-color:#000000; border-right-style:solid; border-right-width:0.75px; border-top-color:#000000; border-top-style:solid; border-top-width:0.75px; padding-left:0.12px; padding-right:0.5px; vertical-align:top; width:157.15px\">")
                .append("<p style=\"margin:5px 0px 0px; orphans:0; text-align:center; widows:0\">")
                .append("<span style=\"font-family:宋体; font-size:11px\">${item.price}</span>")
                .append("</p>")
                .append("</td>")
                .append("<td style=\"  border-left-color:#000000; border-left-style:solid; border-left-width:0.75px; border-right-color:#000000; border-right-style:solid; border-right-width:0.75px; border-top-color:#000000; border-top-style:solid; border-top-width:0.75px; padding-left:0.12px; padding-right:0.5px; vertical-align:top; width:157.15px\">")
                .append("<p style=\"margin:5px 0px 0px; orphans:0; text-align:center; widows:0\">")
                .append("<span style=\"font-family:宋体; font-size:11px\">${item.count}</span>")
                .append("</p>")
                .append("</td>")
                .append("<td style=\"  border-left-color:#000000; border-left-style:solid; border-left-width:0.75px; border-right-color:#000000; border-right-style:solid; border-right-width:0.75px; border-top-color:#000000; border-top-style:solid; border-top-width:0.75px; padding-left:0.12px; padding-right:0.5px; vertical-align:top; width:157.15px\">")
                .append("<p style=\"margin:5px 0px 0px; orphans:0; text-align:center; widows:0\">")
                .append("<span style=\"font-family:宋体; font-size:11px\">${item.amount}</span>")
                .append("</p>")
                .append("</td>")
                .append("<td style=\"  border-left-color:#000000; border-left-style:solid; border-left-width:0.75px; border-right-color:#000000; border-right-style:solid; border-right-width:0.75px; border-top-color:#000000; border-top-style:solid; border-top-width:0.75px; padding-left:0.12px; padding-right:0.5px; vertical-align:top; width:157.15px\">")
                .append("<p style=\"margin:5px 0px 0px; orphans:0; text-align:center; widows:0\">")
                .append("<span style=\"font-family:宋体; font-size:11px\">${item.remark}</span>")
                .append("</p>")
                .append("</td>")
                .append("</tr>")
                .append("<tr style=\"height:23.3px\">")
                .append("<td style=\"  border-left-color:#000000; border-left-style:solid; border-left-width:0.75px; border-right-color:#000000; border-right-style:solid; border-right-width:0.75px; border-top-color:#000000; border-top-style:solid; border-top-width:0.75px; padding-left:0.12px; padding-right:0.5px; vertical-align:top; width:157.15px\">")
                .append("<p style=\"margin:5px 0px 0px; orphans:0; text-align:center; widows:0\">")
                .append("<span style=\"font-family:宋体; font-size:11px\">${item.name}</span>")
                .append("</p>")
                .append("</td>")
                .append("<td style=\"  border-left-color:#000000; border-left-style:solid; border-left-width:0.75px; border-right-color:#000000; border-right-style:solid; border-right-width:0.75px; border-top-color:#000000; border-top-style:solid; border-top-width:0.75px; padding-left:0.12px; padding-right:0.5px; vertical-align:top; width:157.15px\">")
                .append("<p style=\"margin:5px 0px 0px; orphans:0; text-align:center; widows:0\">")
                .append("<span style=\"font-family:宋体; font-size:11px\">${item.spec}</span>")
                .append("</p>")
                .append("</td>")
                .append("<td style=\"  border-left-color:#000000; border-left-style:solid; border-left-width:0.75px; border-right-color:#000000; border-right-style:solid; border-right-width:0.75px; border-top-color:#000000; border-top-style:solid; border-top-width:0.75px; padding-left:0.12px; padding-right:0.5px; vertical-align:top; width:157.15px\">")
                .append("<p style=\"margin:5px 0px 0px; orphans:0; text-align:center; widows:0\">")
                .append("<span style=\"font-family:宋体; font-size:11px\">${item.unit}</span>")
                .append("</p>")
                .append("</td>")
                .append("<td style=\"  border-left-color:#000000; border-left-style:solid; border-left-width:0.75px; border-right-color:#000000; border-right-style:solid; border-right-width:0.75px; border-top-color:#000000; border-top-style:solid; border-top-width:0.75px; padding-left:0.12px; padding-right:0.5px; vertical-align:top; width:157.15px\">")
                .append("<p style=\"margin:5px 0px 0px; orphans:0; text-align:center; widows:0\">")
                .append("<span style=\"font-family:宋体; font-size:11px\">${item.price}</span>")
                .append("</p>")
                .append("</td>")
                .append("<td style=\"  border-left-color:#000000; border-left-style:solid; border-left-width:0.75px; border-right-color:#000000; border-right-style:solid; border-right-width:0.75px; border-top-color:#000000; border-top-style:solid; border-top-width:0.75px; padding-left:0.12px; padding-right:0.5px; vertical-align:top; width:157.15px\">")
                .append("<p style=\"margin:5px 0px 0px; orphans:0; text-align:center; widows:0\">")
                .append("<span style=\"font-family:宋体; font-size:11px\">${item.count}</span>")
                .append("</p>")
                .append("</td>")
                .append("<td style=\"  border-left-color:#000000; border-left-style:solid; border-left-width:0.75px; border-right-color:#000000; border-right-style:solid; border-right-width:0.75px; border-top-color:#000000; border-top-style:solid; border-top-width:0.75px; padding-left:0.12px; padding-right:0.5px; vertical-align:top; width:157.15px\">")
                .append("<p style=\"margin:5px 0px 0px; orphans:0; text-align:center; widows:0\">")
                .append("<span style=\"font-family:宋体; font-size:11px\">${item.amount}</span>")
                .append("</p>")
                .append("</td>")
                .append("<td style=\"  border-left-color:#000000; border-left-style:solid; border-left-width:0.75px; border-right-color:#000000; border-right-style:solid; border-right-width:0.75px; border-top-color:#000000; border-top-style:solid; border-top-width:0.75px; padding-left:0.12px; padding-right:0.5px; vertical-align:top; width:157.15px\">")
                .append("<p style=\"margin:5px 0px 0px; orphans:0; text-align:center; widows:0\">")
                .append("<span style=\"font-family:宋体; font-size:11px\">${item.remark}</span>")
                .append("</p>")
                .append("</td>")
                .append("</tr>")
                .append("<tr style=\"height:23.3px\">")
                .append("<td style=\" border-left-color:#000000; border-left-style:solid; border-left-width:0.75px; border-top-color:#000000; border-top-style:solid; border-top-width:0.75px; padding-left:0.12px; padding-right:0.5px; vertical-align:top; width:157.15px\">")
                .append("<p style=\"margin:5px 0px 0px; orphans:0; text-align:center; widows:0\">")
                .append("<span style=\"font-family:宋体; font-size:15px\">合 计</span>")
                .append("</p>")
                .append("</td>")
                .append("<td style=\" border-left-color:#000000; border-left-style:solid; border-left-width:0.75px; border-top-color:#000000; border-top-style:solid; border-top-width:0.75px; padding-left:0.12px; padding-right:0.5px; vertical-align:top; width:78.7px\">")
                .append("<p style=\"margin:5px 0px 0px; orphans:0; text-align:center; widows:0\">")
                .append("<span style=\"font-family:宋体; font-size:15px\">&#xa0;</span>")
                .append("</p>")
                .append("</td>")
                .append("<td style=\" border-left-color:#000000; border-left-style:solid; border-left-width:0.75px; border-top-color:#000000; border-top-style:solid; border-top-width:0.75px; padding-left:0.12px; padding-right:0.5px; vertical-align:top; width:37.4px\">")
                .append("<p style=\"margin:5px 0px 0px; orphans:0; text-align:center; widows:0\">")
                .append("<span style=\"font-family:宋体; font-size:15px\">&#xa0;</span>")
                .append("</p>")
                .append("</td>")
                .append("<td style=\" border-left-color:#000000; border-left-style:solid; border-left-width:0.75px; border-top-color:#000000; border-top-style:solid; border-top-width:0.75px; padding-left:0.12px; padding-right:0.5px; vertical-align:top; width:62.1px\">")
                .append("<p style=\"margin:5px 0px 0px; orphans:0; text-align:center; widows:0\">")
                .append("<span style=\"font-family:宋体; font-size:15px\">&#xa0;</span>")
                .append("</p>")
                .append("</td>")
                .append("<td style=\" border-left-color:#000000; border-left-style:solid; border-left-width:0.75px; border-top-color:#000000; border-top-style:solid; border-top-width:0.75px; padding-left:0.12px; padding-right:0.5px; vertical-align:top; width:65.95px\">")
                .append("<p style=\"margin:5px 0px 0px; orphans:0; text-align:center; widows:0\">")
                .append("<span style=\"font-family:宋体; font-size:15px\">")
                .append("${total_count}")
                .append("</span>")
                .append("</p>")
                .append("</td>")
                .append("<td style=\" border-left-color:#000000; border-left-style:solid; border-left-width:0.75px; border-top-color:#000000; border-top-style:solid; border-top-width:0.75px; padding-left:0.12px; padding-right:0.5px; vertical-align:top; width:59.7px\">")
                .append("<p style=\"margin:5px 0px 0px; orphans:0; text-align:center; widows:0\">")
                .append("<span style=\"font-family:宋体; font-size:15px\">")
                .append("${total_amount}")
                .append("</span>")
                .append("</p>")
                .append("</td>")
                .append("<td style=\" border-left-color:#000000; border-left-style:solid; border-left-width:0.75px; border-right-color:#000000; border-right-style:solid; border-right-width:0.75px; border-top-color:#000000; border-top-style:solid; border-top-width:0.75px; padding-left:0.12px; padding-right:0.12px; vertical-align:top; width:51.3px\">")
                .append("<p style=\"margin:5px 0px 0px; orphans:0; text-align:center; widows:0\">")
                .append("<span style=\"font-family:宋体; font-size:15px\"></span>")
                .append("</p>")
                .append("</td>")
                .append("</tr>")
                .append("<tr style=\"height:184.3px\">")
                .append("<td colspan=\"7\" style=\" border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:0.75px; border-left-color:#000000; border-left-style:solid; border-left-width:0.75px; border-right-color:#000000; border-right-style:solid; border-right-width:0.75px; border-top-color:#000000; border-top-style:solid; border-top-width:0.75px; padding-left:0.12px; padding-right:0.12px; vertical-align:middle; width:518.3px\">")
                .append("<p style=\"line-height:16.8px; margin:0px 0px 5px 12px; orphans:0; widows:0\">")
                .append("<span style=\"font-family:新宋体; font-size:9px\">备注 （本协议一式两份，甲乙双方各执一份）</span>")
                .append("</p>")
                .append("<ol type=\"1\" style=\"margin:0px; padding-left:0px\">")
                .append("<li style=\"font-family:新宋体; font-size:9px; line-height:16.8px; margin:0px 0px 5px 35.25px; orphans:0; text-indent:0px; widows:0\">")
                .append("<span style=\"font-family:新宋体; font-size:9px\">本订单经双方授权代表签字、盖章后立即生效。</span>")
                .append("</li>")
                .append("<li style=\"font-family:新宋体; font-size:9px; margin:0px 0px 5px 35.25px; orphans:0; text-indent:0px; widows:0\">")
                .append("<span style=\"font-family:新宋体; font-size:9px\">乙方按甲方指定日期将货交运后以邮政快件方式将发票寄至甲方，甲方按双方协议付款方式将款打入乙方指定帐号。</span>")
                .append("</li>")
                .append("<li style=\"font-family:新宋体; font-size:9px; margin:0px 0px 5px 35.25px; orphans:0; text-indent:0px; widows:0\">")
                .append("<span style=\"font-family:新宋体; font-size:9px\">验收及提出异议期限；收到货三日之内以书面形式确认，否则视为合格入库。</span>")
                .append("</li>")
                .append("<li style=\"font-family:新宋体; font-size:9px; margin:0px 0px 5px 35.25px; orphans:0; text-indent:0px; widows:0\">")
                .append("<span style=\"font-family:新宋体; font-size:9px\">质量标准：（1）产品质量符合国家法定标准及其他有关规定的质量标准，（2）产品附产品合格证。</span>")
                .append("</li>")
                .append("<li style=\"font-family:新宋体; font-size:9px; margin:0px 0px 0px 35.25px; orphans:0; text-indent:0px; widows:0\">")
                .append("<span style=\"font-family:新宋体; font-size:9px\">各项数值在小数点后保留两位小数。</span>")
                .append("</li>")
                .append("<li style=\"font-family:新宋体; font-size:9px; line-height:16.8px; margin:0px 14.3px 5px 35.25px; orphans:0; text-indent:0px; widows:0\">")
                .append("<span style=\"font-family:新宋体; font-size:9px\">货至甲方仓库一经验收，所有权即归甲方所有，任何人在甲方调货、借货均视做个人行为（除有乙方总部特别授权并盖章生效的调货单外），乙方不予认可，其后果由甲方自行负责。</span>")
                .append("</li>")
                .append("<li style=\"font-family:新宋体; font-size:9px; margin:0px 0px 5px 35.25px; orphans:0; text-indent:0px; widows:0\">")
                .append("<span style=\"font-family:新宋体; font-size:9px\">双方对该合同如有争议，应友好协商解决；如协商不成时，可在原告所在地以诉讼方式解决。</span>")
                .append("</li>")
                .append("<li style=\"font-family:宋体; font-size:8.5px; margin:0px 14.3px 5px 35.25px; orphans:0; text-indent:0px; widows:0\">")
                .append("<span style=\"font-family:新宋体; font-size:9px\">违约责任：按《中华人民共和国民法典》等有关法律法规处理。</span>")
                .append("</li>")
                .append("</ol>")
                .append("</td>")
                .append("</tr>")
                .append("<tr style=\"height:0px\">")
                .append("<td style=\"width:158.15px; border:none\"></td>")
                .append("<td style=\"width:79.7px; border:none\"></td>")
                .append("<td style=\"width:38.4px; border:none\"></td>")
                .append("<td style=\"width:63.1px; border:none\"></td>")
                .append("<td style=\"width:66.95px; border:none\"></td>")
                .append("<td style=\"width:60.7px; border:none\"></td>")
                .append("<td style=\"width:52.3px; border:none\"></td>")
                .append("</tr>")
                .append("</table>")
                .append("<div style=\"display: flex;justify-content: space-between;\">")
                .append("<div class=\"behalf-box\" style=\"width: 49.5%;position: relative;\">")
                .append("<div class=\"behalf-box-item\" style=\"display: flex;margin-top: 15px;font-size: 11pt;font-family: 宋体;\">")
                .append("<div class=\"behalf-box-item-babel\">甲方代表：</div>")
                .append("<div class=\"behalf-box-item-blank\" style=\"flex: 1;border-bottom: 1px solid #000;font-size: 11pt;font-family: 宋体\"></div>")
                .append("</div>")
                .append("<div class=\"behalf-box-item\" style=\"display: flex;margin-top: 15px;font-size: 11pt;font-family: 宋体;\">")
                .append("<div class=\"behalf-box-item-babel\">甲方公司（盖章）：</div>")
                .append("<div class=\"behalf-box-item-blank\" style=\"flex: 1;border-bottom: 1px solid #000;font-size: 11pt;font-family: 宋体\">")
                .append("${company_name}")
                .append("</div>")
                .append("</div>")
                .append("<div class=\"behalf-box-item\" style=\"display: flex;margin-top: 15px;font-size: 11pt;font-family: 宋体;\">")
                .append("<div class=\"behalf-box-item-babel\">甲方地址：</div>")
                .append("<div class=\"behalf-box-item-blank\" style=\"flex: 1;border-bottom: 1px solid #000;font-size: 11pt;font-family: 宋体\">")
                .append("${company_addr}")
                .append("</div>")
                .append("</div>")
                .append("<div class=\"behalf-box-item\" style=\"display: flex;margin-top: 15px;font-size: 11pt;font-family: 宋体;\">")
                .append("<div class=\"behalf-box-item-babel\">开户银行：</div>")
                .append("<div class=\"behalf-box-item-blank\" style=\"flex: 1;border-bottom: 1px solid #000;font-size: 11pt;font-family: 宋体\">")
                .append("${company_bank}")
                .append("</div>")
                .append("</div>")
                .append("<div class=\"behalf-box-item\" style=\"display: flex;margin-top: 15px;font-size: 11pt;font-family: 宋体;\">")
                .append("<div class=\"behalf-box-item-babel\">银行帐号：</div>")
                .append("<div class=\"behalf-box-item-blank\" style=\"flex: 1;border-bottom: 1px solid #000;font-size: 11pt;font-family: 宋体\">")
                .append("${company_bank_no}")
                .append("</div>")
                .append("</div>")
                .append("<div class=\"behalf-box-item behalf-box-item-two\" style=\"display: flex;margin-top: 15px;font-size: 11pt;font-family: 宋体;display: flex;justify-content: space-between;\">")
                .append("<div class=\"behalf-box-item-box\" style=\"width: 49.5%;display: flex;\">")
                .append("<div class=\"behalf-box-item-babel\">电话：</div>")
                .append("<div class=\"behalf-box-item-blank\" style=\"flex: 1;border-bottom: 1px solid #000;font-size: 11pt;font-family: 宋体\">")
                .append("${company_tel}")
                .append("</div>")
                .append("</div>")
                .append("<div class=\"behalf-box-item-box\" style=\"width: 49.5%;display: flex;\">")
                .append("<div class=\"behalf-box-item-babel\">传真：</div>")
                .append("<div class=\"behalf-box-item-blank\" style=\"flex: 1;border-bottom: 1px solid #000;font-size: 11pt;font-family: 宋体\"></div>")
                .append("</div>")
                .append("</div>")
                .append("</div>")
                .append("<div class=\"behalf-box\" style=\"width: 49.5%;position: relative;\">")
                .append("<div class=\"behalf-box-item\" style=\"display: flex;margin-top: 15px;font-size: 11pt;font-family: 宋体;\">")
                .append("<div class=\"behalf-box-item-babel\">乙方代表：</div>")
                .append("<div class=\"behalf-box-item-blank\" style=\"flex: 1;border-bottom: 1px solid #000;font-size: 11pt;font-family: 宋体\"></div>")
                .append("</div>")
                .append("<div class=\"behalf-box-item\" style=\"display: flex;margin-top: 15px;font-size: 11pt;font-family: 宋体;\">")
                .append("<div class=\"behalf-box-item-babel\">乙方公司（盖章）：</div>")
                .append("<div class=\"behalf-box-item-blank\" style=\"flex: 1;border-bottom: 1px solid #000;font-size: 11pt;font-family: 宋体\">深圳市海王优品健康科技有限公司")
                .append("</div>")
                .append("</div>")
                .append("<div class=\"behalf-box-item\" style=\"display: flex;margin-top: 15px;font-size: 11pt;font-family: 宋体;\">")
                .append("<div class=\"behalf-box-item-babel\">乙方地址：</div>")
                .append("<div class=\"behalf-box-item-blank\" style=\"flex: 1;border-bottom: 1px solid #000;font-size: 11pt;font-family: 宋体\">")
                .append("深圳市南山区粤海街道麻岭社区科技中三路1号海王银河科技大厦25层")
                .append("</div>")
                .append("</div>")
                .append("<div class=\"behalf-box-item\" style=\"display: flex;margin-top: 15px;font-size: 11pt;font-family: 宋体;\">")
                .append("<div class=\"behalf-box-item-babel\">开户银行：</div>")
                .append("<div class=\"behalf-box-item-blank\" style=\"flex: 1;border-bottom: 1px solid #000;font-size: 11pt;font-family: 宋体\">中国工商银行深圳海王支行")
                .append("</div>")
                .append("</div>")
                .append("<div class=\"behalf-box-item\" style=\"display: flex;margin-top: 15px;font-size: 11pt;font-family: 宋体;\">")
                .append("<div class=\"behalf-box-item-babel\">银行帐号：</div>")
                .append("<div class=\"behalf-box-item-blank\" style=\"flex: 1;border-bottom: 1px solid #000;font-size: 11pt;font-family: 宋体\">")
                .append("4000029309200574529")
                .append("</div>")
                .append("</div>")
                .append("<div class=\"behalf-box-item behalf-box-item-two\" style=\"display: flex;margin-top: 15px;font-size: 11pt;font-family: 宋体;display: flex;justify-content: space-between;\">")
                .append("<div class=\"behalf-box-item-box\" style=\"width: 49.5%;display: flex;\">")
                .append("<div class=\"behalf-box-item-babel\">电话：</div>")
                .append("<div class=\"behalf-box-item-blank\" style=\"flex: 1;border-bottom: 1px solid #000;font-size: 11pt;font-family: 宋体\">0755-86568427")
                .append("</div>")
                .append("</div>")
                .append("<div class=\"behalf-box-item-box\" style=\"width: 49.5%;display: flex;\">")
                .append("<div class=\"behalf-box-item-babel\">传真：</div>")
                .append("<div class=\"behalf-box-item-blank\" style=\"flex: 1;border-bottom: 1px solid #000;font-size: 11pt;font-family: 宋体\"></div>")
                .append("</div>")
                .append("</div>")
                .append("<img src=\"https://hwyp-web-pc.oss-cn-shenzhen.aliyuncs.com/seal.png\" class=\"behalf-box-seal\" style=\"position: absolute;top: 50%;left: 50%;transform: translate(-50%,-50%);width: 200px;height: 200px\" alt=\"\" srcset=\"\"></img>")
                .append("</div>")
                .append("</div>")
                .append("</div>")
                .append("</div>")
                .append("</body>")
                .append("</html>");
        return sb.toString();
    }

}
